# Generated by Django 4.2 on 2023-06-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_campussignup_user_campus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propnamesignup',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='propnamesignup',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
