# Generated by Django 4.1.7 on 2023-05-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylisting',
            name='delivery',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Local Pickup'), (2, 'Swapt Delivery')], null=True),
        ),
        migrations.AlterField(
            model_name='inventorylisting',
            name='selling_stage',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Sold', 'Sold')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='swaptlistingmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand'),
        ),
        migrations.AlterField(
            model_name='swaptlistingmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
