# Generated by Django 4.1.7 on 2023-05-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylisting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventorylisting',
            name='pickupmethod',
        ),
        migrations.RemoveField(
            model_name='inventorylisting',
            name='specs',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='specs',
        ),
    ]
