# Generated by Django 4.2 on 2023-05-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '2B: Swapt Listing Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2C: Swapt Listing Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '1B: Inventory Item Colors'},
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={'verbose_name_plural': '1C: Inventory Item Dimensions'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitemattribute',
            options={'verbose_name_plural': '1E: Inventory Item Attributes'},
        ),
        migrations.AlterModelOptions(
            name='inventorylisting',
            options={'verbose_name_plural': '1D. Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='inventorylistingtag',
            options={'verbose_name_plural': '1A: Inventory Listing Tags'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '2E: Swapt Listing Item Attributes'},
        ),
        migrations.AlterModelOptions(
            name='swaptlistingmodel',
            options={'ordering': ('-created_at',), 'verbose_name_plural': '2D. Swapt Listings'},
        ),
        migrations.AlterModelOptions(
            name='swaptlistingtag',
            options={'verbose_name_plural': '2A: Swapt Listing Tags'},
        ),
        migrations.RenameField(
            model_name='inventorylisting',
            old_name='preloaded_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='is_shipped',
            new_name='is_MoveInReady',
        ),
        migrations.RemoveField(
            model_name='inventorylisting',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='inventorylisting',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='preloaded_category',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='street',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='inventorylisting',
            name='isBundled',
            field=models.BooleanField(default=False),
        ),
    ]
