# Generated by Django 4.1.7 on 2023-05-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swapt_prices',
            name='swapt_bundle_listing',
        ),
        migrations.AlterModelOptions(
            name='productoffers',
            options={'verbose_name_plural': 'Users Offers'},
        ),
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name_plural': 'Users AddressBook'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Users Likes'},
        ),
        migrations.DeleteModel(
            name='InventoryListingPrice',
        ),
        migrations.DeleteModel(
            name='Swapt_Prices',
        ),
    ]
