# Generated by Django 4.1.7 on 2023-05-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_swapt_prices_swapt_bundle_listing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwaptPropertyManager',
        ),
    ]
