# Generated by Django 4.2 on 2023-05-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_swaptlistingmodel_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffers',
            old_name='offers_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='productoffers',
            old_name='offers_message',
            new_name='message',
        ),
    ]
