# Generated by Django 4.2 on 2023-05-16 05:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inventorylisting_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffers',
            old_name='offers_text',
            new_name='offers_message',
        ),
        migrations.AlterField(
            model_name='inventorylisting',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='swaptlistingmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='slug'),
        ),
    ]
