# Generated by Django 4.1.7 on 2023-05-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylisting',
            name='category',
            field=models.CharField(choices=[('Living Room Furniture', 'Living Room Furniture'), ('Entryway Furniture', 'Entryway Furniture'), ('Kitchen Furniture', 'Kitchen Furniture'), ('Dining Room Furniture', 'Dining Room Furniture'), ('Office Furniture', 'Office Furniture'), ('Bedroom Furniture', 'Bedroom Furniture'), ('Bathroom Furniture', 'Bathroom Furniture'), ('Laundry Furniture', 'Laundry Furniture'), ('Storage Room Furniture', 'Storage Room Furniture'), ('Outdoor Furniture', 'Outdoor Furniture'), ('Other Furniture', 'Other Furniture')], max_length=50, null=True),
        ),
    ]
