# Generated by Django 4.2 on 2023-04-11 05:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_swaptlistingmodel_city_swaptlistingmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='move_out_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='swaptpropertymanager',
            name='companyname',
            field=models.CharField(default='company', max_length=40),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.swaptlistingmodel'),
        ),
    ]
