# Generated by Django 4.1.7 on 2023-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_swaptpropertymanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='campus',
            field=models.CharField(choices=[('Elon University', 'Elon University')], default='Elon University', max_length=30),
        ),
    ]
