# Generated by Django 4.2 on 2023-06-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_offers_amount_productoffers_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaptlistingmodel',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
