# Generated by Django 4.2 on 2023-06-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_swaptlistingmodel_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylisting',
            old_name='selling_stage',
            new_name='sellingStage',
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='selling_stage',
            new_name='sellingStage',
        ),
    ]
