# Generated by Django 4.1.7 on 2023-05-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_useraddressbook_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swaptcampuspropertynamepair',
            name='listings',
        ),
        migrations.DeleteModel(
            name='InventoryCampusPropertyNamePair',
        ),
        migrations.DeleteModel(
            name='SwaptCampusPropertyNamePair',
        ),
    ]
