# Generated by Django 4.2 on 2023-04-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_swaptlistingmodel_move_out_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmntylisting',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cmntylisting',
            name='category',
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.brand'),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='slug',
            field=models.CharField(default=4, max_length=400),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='specs',
            field=models.TextField(default='nospecs'),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
