# Generated by Django 4.1.7 on 2023-05-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_swaptcampuspropertynamepair_listings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaptpaymenthistory',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.swaptlistingmodel'),
        ),
    ]
