# Generated by Django 4.2 on 2023-06-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_selling_stage_inventorylisting_sellingstage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swaptlistingmodel',
            options={'ordering': ('-createdAt',), 'verbose_name_plural': '2D. Swapt Listings'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='alt_text',
            new_name='altText',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='order_dt',
            new_name='orderDt',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='order_status',
            new_name='orderStatus',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='paid_status',
            new_name='paidStatus',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='total_amt',
            new_name='totalAmt',
        ),
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='invoice_no',
            new_name='invoiceNo',
        ),
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='payment_status',
            new_name='paymentStatus',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_code',
            new_name='colorCode',
        ),
        migrations.RenameField(
            model_name='inventorylisting',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='inventorylisting',
            old_name='publishing_date',
            new_name='publishingDate',
        ),
        migrations.RenameField(
            model_name='inventorylisting',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='inventorylistingtag',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='inventorylistingtag',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='is_MoveInReady',
            new_name='isFeatured',
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='is_featured',
            new_name='isMoveInReady',
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='is_paid',
            new_name='isPaid',
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='move_out_date',
            new_name='moveOutDate',
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='publishing_date',
            new_name='publishingDate',
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
