# Generated by Django 4.2 on 2023-04-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_cmntylisting_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmntylisting',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='desc',
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='detail',
            field=models.TextField(default='detail'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.swaptlistingmodel'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.swaptlistingmodel'),
        ),
    ]
