# Generated by Django 4.2 on 2023-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cmntylisting_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmntylisting',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used - Like New', 'Used - Like New'), ('Used - Decent', 'Used - Decent'), ('Used - Fair', 'Used - Fair')], max_length=50, null=True),
        ),
    ]
