# Generated by Django 4.1.7 on 2023-05-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_swaptpaymenthistory_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwaptListingTransactionRef',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='email',
            field=models.EmailField(default='test@swapt.it', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.swaptlistingmodel'),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='payment_status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('F', 'failed')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='SwaptPaymentHistory',
        ),
    ]
