# Generated by Django 4.1.7 on 2023-04-27 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_swaptlistingmodel_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers_text', models.TextField()),
                ('offers_amount', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.AlterField(
            model_name='swaptlistingmodel',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='order', to='main.cmntylisting'),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.AddField(
            model_name='productoffers',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.swaptlistingmodel'),
        ),
        migrations.AddField(
            model_name='productoffers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
