# Generated by Django 4.1.7 on 2023-04-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0009_productoffers_alter_swaptlistingmodel_listings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CmntyCampusPropertyNamePair',
            new_name='InventoryCampusPropertyNamePair',
        ),
        migrations.RenameModel(
            old_name='CmntyListing',
            new_name='InventoryListing',
        ),
        migrations.RenameModel(
            old_name='CmntyListingPrice',
            new_name='InventoryListingPrice',
        ),
        migrations.RenameModel(
            old_name='CmntyListingTag',
            new_name='InventoryListingTag',
        ),
    ]
