# Generated by Django 4.1.7 on 2023-04-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_cmntycampuspropertynamepair_inventorycampuspropertynamepair_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '7. Inventory Item Attributes'},
        ),
        migrations.AlterField(
            model_name='inventorylisting',
            name='location',
            field=models.CharField(choices=[('Elon, NC', 'Elon NC'), ('Burlington, NC', 'Burlington, NC')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventorylisting'),
        ),
    ]
