# Generated by Django 4.1.7 on 2023-05-02 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='product_imgs/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.swaptlistingmodel')),
            ],
            options={
                'verbose_name_plural': '7. Inventory Item Attributes',
            },
        ),
    ]
